### ISSUE TITLE
gym.error.DependencyNotInstalled: No module named 'mujoco_py.mjlib'.

### ISSUE THREAD

**Issue by chauncygu** [Roythuly/OMPO#1]
Hi, when I run your code, the issue happens:

`gym.error.DependencyNotInstalled: No module named 'mujoco_py.mjlib'. (HINT: you need to install mujoco_py, and also perform the setup instructions here: https://github.com/openai/mujoco-py/.)
`
Could tell me which versions of mujoco and gym that you used in your experiments?

Thanks!

**Comment by Roythuly** [comment]
Thanks for your attention. We choose mujoco==2.3.7, mujoco_py==2.0.2.5, gym==0.13.0.
