### ISSUE TITLE
About baselines

### ISSUE THREAD

**Issue by yingchengyang** [Roythuly/OMPO#2]
Thanks a lot for wuch a wonderful work! I'm curious about the performance of the baselines in these environments, like CaDM, CEMRL. How can I reproduce these baselines? I'd appreciate a lot if you can provide the code of baselines. Thanks a lot!

**Comment by Roythuly** [comment]
Sure! For CaDM, we find its original repo here (https://github.com/younggyoseo/CaDM), and for CEMRL, we find it here (https://github.com/zhenshan-bing/cemrl). Hope it is useful for you!
